#!/usr/bin/env bash
# Configures web-01 Nginx server with a custom header.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/KingDez04 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Error page creation

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP response header
sudo sed -i "s/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Syntax error test
sudo nginx -t

# Restarting nginx after changes

sudo service nginx restart

