#!/usr/bin/env bash
# Configured HAproxy on lb-01 server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 427770-web-01 100.25.181.248:80 check\n\tserver 427770-web-02 52.87.153.235:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart